name: Publish

on:
  release:
    types:
      - created

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requirements
        run: pip install build
      - name: Build distrib
        run: python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
